### ISSUE TITLE
Type: Null Shiny Hunt Failed

### ISSUE THREAD

**Issue by whocares164** [u93132/ShinyHunterUSUM#4]
Hi u93132, 

Thank you for making this program, I used it to shiny hunt Poipole and it worked! I've been trying to hunt type: null and the program got to 11,524 resets. I noticed in the log that it got a shiny percentage of above 70% for one of the resets and then it reset over it to continue the hunt. Is there any way I can lower the % threshold for this hunt? 

Additionally, how would I repack the source code as a .exe file? I have python and pyinstaller installed but couldn't repack due to me being an idiot lol. I'm not sure which file to point pyinstaller to.

Best Regards

**Comment by u93132** [comment]
Hi, 

Thanks for arriving here! Yes, hunting Type: Null has an issue, but I cannot locate it before, as it works well on my N3DS and N2DS. I will try to update the source code later. If you want to modify the parameter and repack the .exe yourself, here is the guideline:

(1) Make sure your Python can run "USUMShinyHunter_GUI.py". The developing environment I am using is IDLE, and it should work for others.
(2) In "Recv.py", replace line 162 from **_if res < self.threshold:_** to **_if res < 0.4:_**. I am using a threshold of 0.15 for all image pattern matching, but it seems like there is some issue here, so please replace the threshold with 0.4 as you said you found 70% shiny (30% normalized distance from being shiny), which is suspicious.
(3) If you want to debug and to printscreen at every run, add this below line 170: **_else: img0.save(self.General.shotpath + '/' + ('%04d' % self.General.start_count) +'.jpg')_** This will help you determine if the shiny hunter falsely skipped a shiny Type: Null.
(4) Run "USUMShinyHunter_GUI.py" to check if everything ok. The operation is the same as with *.exe.

**Note: if you can run this in Python, it is not necessary to pack it in *.exe.

The following is for repacking:
(1) In "make.bat", replace "py -3.11 -m PyInstaller USUMShinyHunter_GUI.spec" with "py -3 -m PyInstaller USUMShinyHunter_GUI.spec". Yes, I made a mistake here, as not everyone is using 3.11.
(2) Make sure you have all the libraries installed. I will upload the requirements later.
(3) Double-click the make.bat if you are under Windows OS, and then wait until the cmd window is gone.

Best

**Comment by whocares164** [comment]
Thank you for your help!

After your message I tried to test it with 10% being considered a shiny by changing line 162 to **if res < 0.9** and it doesn't recognize 13% as a shiny and resets over it. I know 13% is way too low but it is more consistent then getting a 60% for the testing.

Running it in Python helps a lot and I am able to from USUMShinyHunter_GUI.py", for some reason make,bat does nothing for me even with the changes. I think I'm just missing a dependency as py gets me a syntax error. But to get an exe I've just been running **pyinstaller USUMShinyHunter_GUI.spec** and that seems to work for me.

Best Regards

**Comment by whocares164** [comment]
I've realized the 13% is -13% and is why it isn't working. I'll run it with 0.4 as you suggested with the debug and let you know if it works or resets over it for me.

**Comment by u93132** [comment]
Let me know if any good news. Thanks for your testing!

**Comment by whocares164** [comment]
It worked after dropping it to 0.4! Took 1,145 more resets and the shiny rate was 72.00% when the program found it. Thank you again for making the program and helping me out.

**Comment by whocares164** [comment]
Out of curiosity, do you have any plans to make this program for the other 3ds games or for the virtual console titles like pokemon crystal?

**Comment by u93132** [comment]
Wow! Congrats! The issue mainly arises from the colors of the shiny and normal Type: Null being too similar. I will update this magic number, and I believe I can list you as a contributor. All other shiny hunts in USUM measure the time from 'xxx appears!' to 'Go! xxx.' The issue you found should only affect Type: Null, but I am not 100% sure. Hope you enjoy the shiny hunt in the wormhole, lol.

I did plan to extend this to a general scripting language for people to write their own procedures for AFK, but the problem is that NTRstream is still not perfect. I guess your 3DS still crashes sometimes. This is annoying and discourages people from AFKing on the 3DS.

I have a simple Python code without GUI to shiny hunt Serebii in the virtual console. The shiny rate is 1/8192. I can upload it if you want to try. The only thing to do is stand in front of Ilex Forest Shrine, and then run the Python code.

**Comment by whocares164** [comment]
Thank you! Yeah that makes sense and it's a good thing the other measurements are with time because shiny Regice would be a pain otherwise. Haha thank you, it's better than the dynamax adventures to get some of these shinies. Thank you for thinking of putting me as a contributor, it was fun testing the program and changing the code.

Yeah it crashes here and there but I think some of it is due to overheating too. Usually when mine crashed it was in the charger, and warm to the touch.

Yes please, I would love to try out that code for crystal cause I have been procrastinating that shiny hunt for Celebi.

**Comment by u93132** [comment]
I just uploaded the Python code for shiny hunting Celebi. If you have any issues, post them to the new thread I created.

**Comment by whocares164** [comment]
Thank you! I'm going to start hunting it next week. I still need to convert my save to the 3ds and get the GS ball. I'll let you know in the new thread if I run into any issues with the program.
